/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalDocTypeRouteImport } from './routes/legal.$docType'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as InvitationEventIdInvitationIdRouteImport } from './routes/invitation.$eventId.$invitationId'
import { Route as AuthenticatedAppTokensRouteImport } from './routes/_authenticated/app.tokens'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app.profile'
import { Route as AuthenticatedAppNotificationsRouteImport } from './routes/_authenticated/app.notifications'
import { Route as AuthenticatedAppEventsRouteImport } from './routes/_authenticated/app.events'
import { Route as AuthenticatedAppContactsRouteImport } from './routes/_authenticated/app.contacts'
import { Route as AuthenticatedAppAuditRouteImport } from './routes/_authenticated/app.audit'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated/app.admin'
import { Route as AuthenticatedAppEventsIndexRouteImport } from './routes/_authenticated/app.events.index'
import { Route as AuthenticatedAppAdminIndexRouteImport } from './routes/_authenticated/app.admin.index'
import { Route as ApiPublicV1MeRouteImport } from './routes/api/public/v1/me'
import { Route as ApiPublicInvitationsRemindersRouteImport } from './routes/api/public/invitations/reminders'
import { Route as AuthenticatedAppXSplatRouteImport } from './routes/_authenticated/app.x.$'
import { Route as AuthenticatedAppWSplatRouteImport } from './routes/_authenticated/app.w.$'
import { Route as AuthenticatedAppEventsNewRouteImport } from './routes/_authenticated/app.events.new'
import { Route as AuthenticatedAppAdminStudioRouteImport } from './routes/_authenticated/app.admin.studio'
import { Route as AuthenticatedAppAdminScreensRouteImport } from './routes/_authenticated/app.admin.screens'
import { Route as AuthenticatedAppAdminRegistryRouteImport } from './routes/_authenticated/app.admin.registry'
import { Route as AuthenticatedAppAdminMenuComponentsRouteImport } from './routes/_authenticated/app.admin.menu-components'
import { Route as AuthenticatedAppAdminExtensionsRouteImport } from './routes/_authenticated/app.admin.extensions'
import { Route as AuthenticatedAppAdminEventTypesRouteImport } from './routes/_authenticated/app.admin.event-types'
import { Route as AuthenticatedAppAdminContributionsRouteImport } from './routes/_authenticated/app.admin.contributions'
import { Route as AuthenticatedAppAdminContributionTypesRouteImport } from './routes/_authenticated/app.admin.contribution-types'
import { Route as AuthenticatedAppEventsEventIdIndexRouteImport } from './routes/_authenticated/app.events.$eventId.index'
import { Route as AuthenticatedAppEventsEventIdEditRouteImport } from './routes/_authenticated/app.events.$eventId.edit'
import { Route as AuthenticatedAppAdminExtensionsInstallRouteImport } from './routes/_authenticated/app.admin.extensions.install'
import { Route as AuthenticatedAppAdminExtensionsKeyRouteImport } from './routes/_authenticated/app.admin.extensions.$key'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDocTypeRoute = LegalDocTypeRouteImport.update({
  id: '/legal/$docType',
  path: '/legal/$docType',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const InvitationEventIdInvitationIdRoute =
  InvitationEventIdInvitationIdRouteImport.update({
    id: '/invitation/$eventId/$invitationId',
    path: '/invitation/$eventId/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppTokensRoute = AuthenticatedAppTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppNotificationsRoute =
  AuthenticatedAppNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEventsRoute = AuthenticatedAppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppContactsRoute =
  AuthenticatedAppContactsRouteImport.update({
    id: '/contacts',
    path: '/contacts',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAuditRoute = AuthenticatedAppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppEventsIndexRoute =
  AuthenticatedAppEventsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppEventsRoute,
  } as any)
const AuthenticatedAppAdminIndexRoute =
  AuthenticatedAppAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const ApiPublicV1MeRoute = ApiPublicV1MeRouteImport.update({
  id: '/api/public/v1/me',
  path: '/api/public/v1/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInvitationsRemindersRoute =
  ApiPublicInvitationsRemindersRouteImport.update({
    id: '/api/public/invitations/reminders',
    path: '/api/public/invitations/reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppXSplatRoute = AuthenticatedAppXSplatRouteImport.update({
  id: '/x/$',
  path: '/x/$',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppWSplatRoute = AuthenticatedAppWSplatRouteImport.update({
  id: '/w/$',
  path: '/w/$',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppEventsNewRoute =
  AuthenticatedAppEventsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAppEventsRoute,
  } as any)
const AuthenticatedAppAdminStudioRoute =
  AuthenticatedAppAdminStudioRouteImport.update({
    id: '/studio',
    path: '/studio',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminScreensRoute =
  AuthenticatedAppAdminScreensRouteImport.update({
    id: '/screens',
    path: '/screens',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminRegistryRoute =
  AuthenticatedAppAdminRegistryRouteImport.update({
    id: '/registry',
    path: '/registry',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminMenuComponentsRoute =
  AuthenticatedAppAdminMenuComponentsRouteImport.update({
    id: '/menu-components',
    path: '/menu-components',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminExtensionsRoute =
  AuthenticatedAppAdminExtensionsRouteImport.update({
    id: '/extensions',
    path: '/extensions',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminEventTypesRoute =
  AuthenticatedAppAdminEventTypesRouteImport.update({
    id: '/event-types',
    path: '/event-types',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminContributionsRoute =
  AuthenticatedAppAdminContributionsRouteImport.update({
    id: '/contributions',
    path: '/contributions',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminContributionTypesRoute =
  AuthenticatedAppAdminContributionTypesRouteImport.update({
    id: '/contribution-types',
    path: '/contribution-types',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppEventsEventIdIndexRoute =
  AuthenticatedAppEventsEventIdIndexRouteImport.update({
    id: '/$eventId/',
    path: '/$eventId/',
    getParentRoute: () => AuthenticatedAppEventsRoute,
  } as any)
const AuthenticatedAppEventsEventIdEditRoute =
  AuthenticatedAppEventsEventIdEditRouteImport.update({
    id: '/$eventId/edit',
    path: '/$eventId/edit',
    getParentRoute: () => AuthenticatedAppEventsRoute,
  } as any)
const AuthenticatedAppAdminExtensionsInstallRoute =
  AuthenticatedAppAdminExtensionsInstallRouteImport.update({
    id: '/install',
    path: '/install',
    getParentRoute: () => AuthenticatedAppAdminExtensionsRoute,
  } as any)
const AuthenticatedAppAdminExtensionsKeyRoute =
  AuthenticatedAppAdminExtensionsKeyRouteImport.update({
    id: '/$key',
    path: '/$key',
    getParentRoute: () => AuthenticatedAppAdminExtensionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/legal/$docType': typeof LegalDocTypeRoute
  '/app/admin': typeof AuthenticatedAppAdminRouteWithChildren
  '/app/audit': typeof AuthenticatedAppAuditRoute
  '/app/contacts': typeof AuthenticatedAppContactsRoute
  '/app/events': typeof AuthenticatedAppEventsRouteWithChildren
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/tokens': typeof AuthenticatedAppTokensRoute
  '/invitation/$eventId/$invitationId': typeof InvitationEventIdInvitationIdRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/admin/contribution-types': typeof AuthenticatedAppAdminContributionTypesRoute
  '/app/admin/contributions': typeof AuthenticatedAppAdminContributionsRoute
  '/app/admin/event-types': typeof AuthenticatedAppAdminEventTypesRoute
  '/app/admin/extensions': typeof AuthenticatedAppAdminExtensionsRouteWithChildren
  '/app/admin/menu-components': typeof AuthenticatedAppAdminMenuComponentsRoute
  '/app/admin/registry': typeof AuthenticatedAppAdminRegistryRoute
  '/app/admin/screens': typeof AuthenticatedAppAdminScreensRoute
  '/app/admin/studio': typeof AuthenticatedAppAdminStudioRoute
  '/app/events/new': typeof AuthenticatedAppEventsNewRoute
  '/app/w/$': typeof AuthenticatedAppWSplatRoute
  '/app/x/$': typeof AuthenticatedAppXSplatRoute
  '/api/public/invitations/reminders': typeof ApiPublicInvitationsRemindersRoute
  '/api/public/v1/me': typeof ApiPublicV1MeRoute
  '/app/admin/': typeof AuthenticatedAppAdminIndexRoute
  '/app/events/': typeof AuthenticatedAppEventsIndexRoute
  '/app/admin/extensions/$key': typeof AuthenticatedAppAdminExtensionsKeyRoute
  '/app/admin/extensions/install': typeof AuthenticatedAppAdminExtensionsInstallRoute
  '/app/events/$eventId/edit': typeof AuthenticatedAppEventsEventIdEditRoute
  '/app/events/$eventId/': typeof AuthenticatedAppEventsEventIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/legal/$docType': typeof LegalDocTypeRoute
  '/app/audit': typeof AuthenticatedAppAuditRoute
  '/app/contacts': typeof AuthenticatedAppContactsRoute
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/tokens': typeof AuthenticatedAppTokensRoute
  '/invitation/$eventId/$invitationId': typeof InvitationEventIdInvitationIdRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/admin/contribution-types': typeof AuthenticatedAppAdminContributionTypesRoute
  '/app/admin/contributions': typeof AuthenticatedAppAdminContributionsRoute
  '/app/admin/event-types': typeof AuthenticatedAppAdminEventTypesRoute
  '/app/admin/extensions': typeof AuthenticatedAppAdminExtensionsRouteWithChildren
  '/app/admin/menu-components': typeof AuthenticatedAppAdminMenuComponentsRoute
  '/app/admin/registry': typeof AuthenticatedAppAdminRegistryRoute
  '/app/admin/screens': typeof AuthenticatedAppAdminScreensRoute
  '/app/admin/studio': typeof AuthenticatedAppAdminStudioRoute
  '/app/events/new': typeof AuthenticatedAppEventsNewRoute
  '/app/w/$': typeof AuthenticatedAppWSplatRoute
  '/app/x/$': typeof AuthenticatedAppXSplatRoute
  '/api/public/invitations/reminders': typeof ApiPublicInvitationsRemindersRoute
  '/api/public/v1/me': typeof ApiPublicV1MeRoute
  '/app/admin': typeof AuthenticatedAppAdminIndexRoute
  '/app/events': typeof AuthenticatedAppEventsIndexRoute
  '/app/admin/extensions/$key': typeof AuthenticatedAppAdminExtensionsKeyRoute
  '/app/admin/extensions/install': typeof AuthenticatedAppAdminExtensionsInstallRoute
  '/app/events/$eventId/edit': typeof AuthenticatedAppEventsEventIdEditRoute
  '/app/events/$eventId': typeof AuthenticatedAppEventsEventIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/legal/$docType': typeof LegalDocTypeRoute
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRouteWithChildren
  '/_authenticated/app/audit': typeof AuthenticatedAppAuditRoute
  '/_authenticated/app/contacts': typeof AuthenticatedAppContactsRoute
  '/_authenticated/app/events': typeof AuthenticatedAppEventsRouteWithChildren
  '/_authenticated/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/tokens': typeof AuthenticatedAppTokensRoute
  '/invitation/$eventId/$invitationId': typeof InvitationEventIdInvitationIdRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/admin/contribution-types': typeof AuthenticatedAppAdminContributionTypesRoute
  '/_authenticated/app/admin/contributions': typeof AuthenticatedAppAdminContributionsRoute
  '/_authenticated/app/admin/event-types': typeof AuthenticatedAppAdminEventTypesRoute
  '/_authenticated/app/admin/extensions': typeof AuthenticatedAppAdminExtensionsRouteWithChildren
  '/_authenticated/app/admin/menu-components': typeof AuthenticatedAppAdminMenuComponentsRoute
  '/_authenticated/app/admin/registry': typeof AuthenticatedAppAdminRegistryRoute
  '/_authenticated/app/admin/screens': typeof AuthenticatedAppAdminScreensRoute
  '/_authenticated/app/admin/studio': typeof AuthenticatedAppAdminStudioRoute
  '/_authenticated/app/events/new': typeof AuthenticatedAppEventsNewRoute
  '/_authenticated/app/w/$': typeof AuthenticatedAppWSplatRoute
  '/_authenticated/app/x/$': typeof AuthenticatedAppXSplatRoute
  '/api/public/invitations/reminders': typeof ApiPublicInvitationsRemindersRoute
  '/api/public/v1/me': typeof ApiPublicV1MeRoute
  '/_authenticated/app/admin/': typeof AuthenticatedAppAdminIndexRoute
  '/_authenticated/app/events/': typeof AuthenticatedAppEventsIndexRoute
  '/_authenticated/app/admin/extensions/$key': typeof AuthenticatedAppAdminExtensionsKeyRoute
  '/_authenticated/app/admin/extensions/install': typeof AuthenticatedAppAdminExtensionsInstallRoute
  '/_authenticated/app/events/$eventId/edit': typeof AuthenticatedAppEventsEventIdEditRoute
  '/_authenticated/app/events/$eventId/': typeof AuthenticatedAppEventsEventIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/app'
    | '/legal/$docType'
    | '/app/admin'
    | '/app/audit'
    | '/app/contacts'
    | '/app/events'
    | '/app/notifications'
    | '/app/profile'
    | '/app/tokens'
    | '/invitation/$eventId/$invitationId'
    | '/app/'
    | '/app/admin/contribution-types'
    | '/app/admin/contributions'
    | '/app/admin/event-types'
    | '/app/admin/extensions'
    | '/app/admin/menu-components'
    | '/app/admin/registry'
    | '/app/admin/screens'
    | '/app/admin/studio'
    | '/app/events/new'
    | '/app/w/$'
    | '/app/x/$'
    | '/api/public/invitations/reminders'
    | '/api/public/v1/me'
    | '/app/admin/'
    | '/app/events/'
    | '/app/admin/extensions/$key'
    | '/app/admin/extensions/install'
    | '/app/events/$eventId/edit'
    | '/app/events/$eventId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/legal/$docType'
    | '/app/audit'
    | '/app/contacts'
    | '/app/notifications'
    | '/app/profile'
    | '/app/tokens'
    | '/invitation/$eventId/$invitationId'
    | '/app'
    | '/app/admin/contribution-types'
    | '/app/admin/contributions'
    | '/app/admin/event-types'
    | '/app/admin/extensions'
    | '/app/admin/menu-components'
    | '/app/admin/registry'
    | '/app/admin/screens'
    | '/app/admin/studio'
    | '/app/events/new'
    | '/app/w/$'
    | '/app/x/$'
    | '/api/public/invitations/reminders'
    | '/api/public/v1/me'
    | '/app/admin'
    | '/app/events'
    | '/app/admin/extensions/$key'
    | '/app/admin/extensions/install'
    | '/app/events/$eventId/edit'
    | '/app/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/_authenticated/app'
    | '/legal/$docType'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/audit'
    | '/_authenticated/app/contacts'
    | '/_authenticated/app/events'
    | '/_authenticated/app/notifications'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/tokens'
    | '/invitation/$eventId/$invitationId'
    | '/_authenticated/app/'
    | '/_authenticated/app/admin/contribution-types'
    | '/_authenticated/app/admin/contributions'
    | '/_authenticated/app/admin/event-types'
    | '/_authenticated/app/admin/extensions'
    | '/_authenticated/app/admin/menu-components'
    | '/_authenticated/app/admin/registry'
    | '/_authenticated/app/admin/screens'
    | '/_authenticated/app/admin/studio'
    | '/_authenticated/app/events/new'
    | '/_authenticated/app/w/$'
    | '/_authenticated/app/x/$'
    | '/api/public/invitations/reminders'
    | '/api/public/v1/me'
    | '/_authenticated/app/admin/'
    | '/_authenticated/app/events/'
    | '/_authenticated/app/admin/extensions/$key'
    | '/_authenticated/app/admin/extensions/install'
    | '/_authenticated/app/events/$eventId/edit'
    | '/_authenticated/app/events/$eventId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  LegalDocTypeRoute: typeof LegalDocTypeRoute
  InvitationEventIdInvitationIdRoute: typeof InvitationEventIdInvitationIdRoute
  ApiPublicInvitationsRemindersRoute: typeof ApiPublicInvitationsRemindersRoute
  ApiPublicV1MeRoute: typeof ApiPublicV1MeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$docType': {
      id: '/legal/$docType'
      path: '/legal/$docType'
      fullPath: '/legal/$docType'
      preLoaderRoute: typeof LegalDocTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/invitation/$eventId/$invitationId': {
      id: '/invitation/$eventId/$invitationId'
      path: '/invitation/$eventId/$invitationId'
      fullPath: '/invitation/$eventId/$invitationId'
      preLoaderRoute: typeof InvitationEventIdInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/tokens': {
      id: '/_authenticated/app/tokens'
      path: '/tokens'
      fullPath: '/app/tokens'
      preLoaderRoute: typeof AuthenticatedAppTokensRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/notifications': {
      id: '/_authenticated/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AuthenticatedAppNotificationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/events': {
      id: '/_authenticated/app/events'
      path: '/events'
      fullPath: '/app/events'
      preLoaderRoute: typeof AuthenticatedAppEventsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/contacts': {
      id: '/_authenticated/app/contacts'
      path: '/contacts'
      fullPath: '/app/contacts'
      preLoaderRoute: typeof AuthenticatedAppContactsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/audit': {
      id: '/_authenticated/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AuthenticatedAppAuditRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/events/': {
      id: '/_authenticated/app/events/'
      path: '/'
      fullPath: '/app/events/'
      preLoaderRoute: typeof AuthenticatedAppEventsIndexRouteImport
      parentRoute: typeof AuthenticatedAppEventsRoute
    }
    '/_authenticated/app/admin/': {
      id: '/_authenticated/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AuthenticatedAppAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/api/public/v1/me': {
      id: '/api/public/v1/me'
      path: '/api/public/v1/me'
      fullPath: '/api/public/v1/me'
      preLoaderRoute: typeof ApiPublicV1MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/invitations/reminders': {
      id: '/api/public/invitations/reminders'
      path: '/api/public/invitations/reminders'
      fullPath: '/api/public/invitations/reminders'
      preLoaderRoute: typeof ApiPublicInvitationsRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/x/$': {
      id: '/_authenticated/app/x/$'
      path: '/x/$'
      fullPath: '/app/x/$'
      preLoaderRoute: typeof AuthenticatedAppXSplatRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/w/$': {
      id: '/_authenticated/app/w/$'
      path: '/w/$'
      fullPath: '/app/w/$'
      preLoaderRoute: typeof AuthenticatedAppWSplatRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/events/new': {
      id: '/_authenticated/app/events/new'
      path: '/new'
      fullPath: '/app/events/new'
      preLoaderRoute: typeof AuthenticatedAppEventsNewRouteImport
      parentRoute: typeof AuthenticatedAppEventsRoute
    }
    '/_authenticated/app/admin/studio': {
      id: '/_authenticated/app/admin/studio'
      path: '/studio'
      fullPath: '/app/admin/studio'
      preLoaderRoute: typeof AuthenticatedAppAdminStudioRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/screens': {
      id: '/_authenticated/app/admin/screens'
      path: '/screens'
      fullPath: '/app/admin/screens'
      preLoaderRoute: typeof AuthenticatedAppAdminScreensRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/registry': {
      id: '/_authenticated/app/admin/registry'
      path: '/registry'
      fullPath: '/app/admin/registry'
      preLoaderRoute: typeof AuthenticatedAppAdminRegistryRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/menu-components': {
      id: '/_authenticated/app/admin/menu-components'
      path: '/menu-components'
      fullPath: '/app/admin/menu-components'
      preLoaderRoute: typeof AuthenticatedAppAdminMenuComponentsRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/extensions': {
      id: '/_authenticated/app/admin/extensions'
      path: '/extensions'
      fullPath: '/app/admin/extensions'
      preLoaderRoute: typeof AuthenticatedAppAdminExtensionsRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/event-types': {
      id: '/_authenticated/app/admin/event-types'
      path: '/event-types'
      fullPath: '/app/admin/event-types'
      preLoaderRoute: typeof AuthenticatedAppAdminEventTypesRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/contributions': {
      id: '/_authenticated/app/admin/contributions'
      path: '/contributions'
      fullPath: '/app/admin/contributions'
      preLoaderRoute: typeof AuthenticatedAppAdminContributionsRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/contribution-types': {
      id: '/_authenticated/app/admin/contribution-types'
      path: '/contribution-types'
      fullPath: '/app/admin/contribution-types'
      preLoaderRoute: typeof AuthenticatedAppAdminContributionTypesRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/events/$eventId/': {
      id: '/_authenticated/app/events/$eventId/'
      path: '/$eventId'
      fullPath: '/app/events/$eventId/'
      preLoaderRoute: typeof AuthenticatedAppEventsEventIdIndexRouteImport
      parentRoute: typeof AuthenticatedAppEventsRoute
    }
    '/_authenticated/app/events/$eventId/edit': {
      id: '/_authenticated/app/events/$eventId/edit'
      path: '/$eventId/edit'
      fullPath: '/app/events/$eventId/edit'
      preLoaderRoute: typeof AuthenticatedAppEventsEventIdEditRouteImport
      parentRoute: typeof AuthenticatedAppEventsRoute
    }
    '/_authenticated/app/admin/extensions/install': {
      id: '/_authenticated/app/admin/extensions/install'
      path: '/install'
      fullPath: '/app/admin/extensions/install'
      preLoaderRoute: typeof AuthenticatedAppAdminExtensionsInstallRouteImport
      parentRoute: typeof AuthenticatedAppAdminExtensionsRoute
    }
    '/_authenticated/app/admin/extensions/$key': {
      id: '/_authenticated/app/admin/extensions/$key'
      path: '/$key'
      fullPath: '/app/admin/extensions/$key'
      preLoaderRoute: typeof AuthenticatedAppAdminExtensionsKeyRouteImport
      parentRoute: typeof AuthenticatedAppAdminExtensionsRoute
    }
  }
}

interface AuthenticatedAppAdminExtensionsRouteChildren {
  AuthenticatedAppAdminExtensionsKeyRoute: typeof AuthenticatedAppAdminExtensionsKeyRoute
  AuthenticatedAppAdminExtensionsInstallRoute: typeof AuthenticatedAppAdminExtensionsInstallRoute
}

const AuthenticatedAppAdminExtensionsRouteChildren: AuthenticatedAppAdminExtensionsRouteChildren =
  {
    AuthenticatedAppAdminExtensionsKeyRoute:
      AuthenticatedAppAdminExtensionsKeyRoute,
    AuthenticatedAppAdminExtensionsInstallRoute:
      AuthenticatedAppAdminExtensionsInstallRoute,
  }

const AuthenticatedAppAdminExtensionsRouteWithChildren =
  AuthenticatedAppAdminExtensionsRoute._addFileChildren(
    AuthenticatedAppAdminExtensionsRouteChildren,
  )

interface AuthenticatedAppAdminRouteChildren {
  AuthenticatedAppAdminContributionTypesRoute: typeof AuthenticatedAppAdminContributionTypesRoute
  AuthenticatedAppAdminContributionsRoute: typeof AuthenticatedAppAdminContributionsRoute
  AuthenticatedAppAdminEventTypesRoute: typeof AuthenticatedAppAdminEventTypesRoute
  AuthenticatedAppAdminExtensionsRoute: typeof AuthenticatedAppAdminExtensionsRouteWithChildren
  AuthenticatedAppAdminMenuComponentsRoute: typeof AuthenticatedAppAdminMenuComponentsRoute
  AuthenticatedAppAdminRegistryRoute: typeof AuthenticatedAppAdminRegistryRoute
  AuthenticatedAppAdminScreensRoute: typeof AuthenticatedAppAdminScreensRoute
  AuthenticatedAppAdminStudioRoute: typeof AuthenticatedAppAdminStudioRoute
  AuthenticatedAppAdminIndexRoute: typeof AuthenticatedAppAdminIndexRoute
}

const AuthenticatedAppAdminRouteChildren: AuthenticatedAppAdminRouteChildren = {
  AuthenticatedAppAdminContributionTypesRoute:
    AuthenticatedAppAdminContributionTypesRoute,
  AuthenticatedAppAdminContributionsRoute:
    AuthenticatedAppAdminContributionsRoute,
  AuthenticatedAppAdminEventTypesRoute: AuthenticatedAppAdminEventTypesRoute,
  AuthenticatedAppAdminExtensionsRoute:
    AuthenticatedAppAdminExtensionsRouteWithChildren,
  AuthenticatedAppAdminMenuComponentsRoute:
    AuthenticatedAppAdminMenuComponentsRoute,
  AuthenticatedAppAdminRegistryRoute: AuthenticatedAppAdminRegistryRoute,
  AuthenticatedAppAdminScreensRoute: AuthenticatedAppAdminScreensRoute,
  AuthenticatedAppAdminStudioRoute: AuthenticatedAppAdminStudioRoute,
  AuthenticatedAppAdminIndexRoute: AuthenticatedAppAdminIndexRoute,
}

const AuthenticatedAppAdminRouteWithChildren =
  AuthenticatedAppAdminRoute._addFileChildren(
    AuthenticatedAppAdminRouteChildren,
  )

interface AuthenticatedAppEventsRouteChildren {
  AuthenticatedAppEventsNewRoute: typeof AuthenticatedAppEventsNewRoute
  AuthenticatedAppEventsIndexRoute: typeof AuthenticatedAppEventsIndexRoute
  AuthenticatedAppEventsEventIdEditRoute: typeof AuthenticatedAppEventsEventIdEditRoute
  AuthenticatedAppEventsEventIdIndexRoute: typeof AuthenticatedAppEventsEventIdIndexRoute
}

const AuthenticatedAppEventsRouteChildren: AuthenticatedAppEventsRouteChildren =
  {
    AuthenticatedAppEventsNewRoute: AuthenticatedAppEventsNewRoute,
    AuthenticatedAppEventsIndexRoute: AuthenticatedAppEventsIndexRoute,
    AuthenticatedAppEventsEventIdEditRoute:
      AuthenticatedAppEventsEventIdEditRoute,
    AuthenticatedAppEventsEventIdIndexRoute:
      AuthenticatedAppEventsEventIdIndexRoute,
  }

const AuthenticatedAppEventsRouteWithChildren =
  AuthenticatedAppEventsRoute._addFileChildren(
    AuthenticatedAppEventsRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRouteWithChildren
  AuthenticatedAppAuditRoute: typeof AuthenticatedAppAuditRoute
  AuthenticatedAppContactsRoute: typeof AuthenticatedAppContactsRoute
  AuthenticatedAppEventsRoute: typeof AuthenticatedAppEventsRouteWithChildren
  AuthenticatedAppNotificationsRoute: typeof AuthenticatedAppNotificationsRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppTokensRoute: typeof AuthenticatedAppTokensRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppWSplatRoute: typeof AuthenticatedAppWSplatRoute
  AuthenticatedAppXSplatRoute: typeof AuthenticatedAppXSplatRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRouteWithChildren,
  AuthenticatedAppAuditRoute: AuthenticatedAppAuditRoute,
  AuthenticatedAppContactsRoute: AuthenticatedAppContactsRoute,
  AuthenticatedAppEventsRoute: AuthenticatedAppEventsRouteWithChildren,
  AuthenticatedAppNotificationsRoute: AuthenticatedAppNotificationsRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppTokensRoute: AuthenticatedAppTokensRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppWSplatRoute: AuthenticatedAppWSplatRoute,
  AuthenticatedAppXSplatRoute: AuthenticatedAppXSplatRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  LegalDocTypeRoute: LegalDocTypeRoute,
  InvitationEventIdInvitationIdRoute: InvitationEventIdInvitationIdRoute,
  ApiPublicInvitationsRemindersRoute: ApiPublicInvitationsRemindersRoute,
  ApiPublicV1MeRoute: ApiPublicV1MeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
