// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdzzkijsdtsexsrcfiwb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkenpraWpzZHRzZXhzcmNmaXdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODEyMDIxNDIsImV4cCI6MjA5Njc3ODE0Mn0.PEK1DGbG1VbgZTiUsd6LRGd9FBgCeJtg-iKec7k8pss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});